FROM zookeeper:3.4.13

ARG JMX_PROMETHEUS_JAVAAGENT=jmx_prometheus_javaagent
ARG JMX_PROMETHEUS_JAVAAGENT_VERSION=0.3.1
ARG JMX_PROMETHEUS_JAVAAGENT_DIR=/usr/local/share
ARG JMX_PROMETHEUS_JAVAAGENT_CONFIG_DIR=/etc/jmx-exporter

RUN set -x; \
    wget -q --directory-prefix=${JMX_PROMETHEUS_JAVAAGENT_DIR} "https://repo1.maven.org/maven2/io/prometheus/jmx/${JMX_PROMETHEUS_JAVAAGENT}/${JMX_PROMETHEUS_JAVAAGENT_VERSION}/${JMX_PROMETHEUS_JAVAAGENT}-${JMX_PROMETHEUS_JAVAAGENT_VERSION}.jar"; \
    mkdir -p ${JMX_PROMETHEUS_JAVAAGENT_CONFIG_DIR}; \
    wget -q --directory-prefix=${JMX_PROMETHEUS_JAVAAGENT_CONFIG_DIR} "https://raw.githubusercontent.com/prometheus/jmx_exporter/parent-${JMX_PROMETHEUS_JAVAAGENT_VERSION}/example_configs/zookeeper.yaml"

ENV ZOO_PROMETHEUS_PORT=9141
ENV SERVER_JVMFLAGS="-javaagent:${JMX_PROMETHEUS_JAVAAGENT_DIR}/${JMX_PROMETHEUS_JAVAAGENT}-${JMX_PROMETHEUS_JAVAAGENT_VERSION}.jar=$ZOO_PROMETHEUS_PORT:${JMX_PROMETHEUS_JAVAAGENT_CONFIG_DIR}/zookeeper.yaml"

EXPOSE ${ZOO_PROMETHEUS_PORT}
